# Generated by Django 2.1.3 on 2018-11-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('website_link', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('linkedin_link', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_where', models.CharField(max_length=200)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField(blank=True)),
                ('is_going_on', models.BooleanField(default=False)),
                ('grade', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=200)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField(blank=True)),
                ('is_going_on', models.BooleanField(default=False)),
                ('time_worked', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
