# Generated by Django 2.1.3 on 2018-11-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20181111_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
