# Generated by Django 2.1.3 on 2018-11-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20181111_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='time_worked',
            field=models.CharField(max_length=100),
        ),
    ]
