# Generated by Django 2.1.3 on 2018-11-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20181111_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
