# Generated by Django 2.1.3 on 2018-11-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20181112_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='what',
            field=models.CharField(default='undergraduate', max_length=30),
            preserve_default=False,
        ),
    ]
